### PR TITLE
Turn repeated errors into notice and replace error_logger with logger

### LINKED ISSUE #61: eredis_client:maybe_reconnect logs are too verbose
Mainly visual/convenience issue: if the eredis_client processes are calling `maybe_reconnect` repeatedly, it creates a lot of "ERROR REPORT" messages in the erlang logs. By default each client process tries to connect once every 100ms, and if `eredis_cluster` is used as the supervisor tree for the clients then there are 10 clients per redis server.

A common trivial scenario is when a redis server is intentionally removed (scaling down cluster). In this case reconnections will fail with connection reset, while the original connection will have been severed with etimedout or connection reset (in the `eredis_cluster` usage scenario, eventually the slot maps are refreshed and the clients towards the deleted server are terminated). It works fine, but a lot of spam is generated in the logs.

I wonder if it could be improved; some ideas to consider:
- only log the report & reason on first reconnect attempt (ie. the original reason for the reconnect, not the reason from the last attempt each time)?
- if the repeated (ie. not initial) reconnect attempts are logged, maybe the level there should be debug or info, not error
- only log the report & reason if the Reason is different than last time (common case is where the same reason is repeated many times, like when the redis server leaves and is no longer listening)

### PR DESCRIPTION
**Pull request by zuiderkwast**
Replace error_logger with logger. The latter allows more configuration and filtering.

Turn some errors into warnings or notices. Notably, repeated failure to connect can indicate that the Redis node is down. In this case we don't want to flood the log.

Fixes #61.

### CODE REVIEW

**Comment by zuiderkwast** [comment]
@e-kmisk Please have a look.

@dhruvjain99 I changed the non-fatal sentinel errors into warnings. This is when there are other sentinels to try. Please complain if you don't like it.

**Review by bjosv — APPROVED** [review]
LGTM

**Comment by e-kmisk** [comment]
> @e-kmisk Please have a look.
> 
> @dhruvjain99 I changed the non-fatal sentinel errors into warnings. This is when there are other sentinels to try. Please complain if you don't like it.

Thanks for this, it looks promising.

File: src/eredis_client.erl [hunk 1]
```diff
@@ -606,9 +610,17 @@ maybe_reconnect(Reason,
...
-            {noreply, schedule_reconnect(NewReason, State1)}
+            ?LOG_NOTICE("eredis: Reconnect failed: ~p", [NewReason]),
+            {noreply, schedule_reconnect(State1)}
     end.
 
+log_reconnect(retry, _Host, _Port) ->
+    %% Don't flood the log for every retry, in case the Redis node is down.
+    ok;
+log_reconnect(Reason, Host, Port) ->
+    ?LOG_WARNING("eredis: Re-establishing connection to ~p:~p due to ~p",
```
Comment (e-kmisk) [inline src/eredis_client.erl:621]: Could we also log the `self()` pid? When this is managed via eredis_cluster, that is useful info.

Comment (zuiderkwast) [reply src/eredis_client.erl:621]: Sure. Can I drop the `eredis:` prefix too? The module name is somewhere in the log entry anyway.

Comment (zuiderkwast) [reply src/eredis_client.erl:621]: `("~p reconnecting to ~p:~p due to ~p", [self(), Host, Port, Reason])` OK?

Comment (e-kmisk) [reply src/eredis_client.erl:621]: I tried it and I don't see module name, am I missing something?
```
1> f(),Host="127.0.0.1",Port=6379,Reason=econnrefused,logger:warning("~p reconnecting to ~p:~p due to ~p", [self(), Host, Port, Reason])
1> .
=WARNING REPORT==== 22-Jul-2022::14:29:47.860134 ===
<0.80.0> reconnecting to "127.0.0.1":6379 due to econnrefused
```

Comment (zuiderkwast) [reply src/eredis_client.erl:621]: The macros `?LOG_WARNING` etc. add file, line, mfa, etc. to the log entry metadata. See https://www.erlang.org/doc/man/logger.html#type-metadata.

To show it in the formatted log message, try something like this:

```Erlang
logger:update_handler_config(default, #{formatter => {logger_formatter, #{template => [time," ",level," at ", file, ":", line, "\n", msg,"\n"]}}}).
```

Comment (zuiderkwast) [reply src/eredis_client.erl:621]: Even the pid is in the log entry metadata.

Comment (e-kmisk) [reply src/eredis_client.erl:621]: Thanks for explaining. I guess there is no need to explicitly add the pid then?

**Comment by e-kmisk** [comment]
Could this be merged? We'd like to uplift eredis soon, but we need a release tag to start the process (I guess that will be 1.7.0)

File: src/eredis_client.erl [hunk 2]
```diff
@@ -230,13 +231,14 @@ handle_info(initiate_connection, #state{socket = undefined} = State) ->
         {ok, NewState} ->
             {noreply, NewState};
         {error, Reason} ->
-            {noreply, schedule_reconnect(Reason, State)}
+            ?LOG_WARNING("eredis: Initial connect failed: ~p", [Reason]),
```
Comment (bjosv) [inline src/eredis_client.erl:234]:
```suggestion
            ?LOG_WARNING("Initial connect failed: ~p", [Reason]),
```

Removing `eredis`, can be given via metadata [mfa](https://www.erlang.org/doc/man/logger.html#type-metadata)

File: src/eredis_client.erl [hunk 3]
```diff
@@ -336,7 +338,7 @@ reply(Value, Queue) ->
             queue:in_r({N - 1, From, [Value | Replies]}, NewQueue);
         {empty, Queue} ->
             %% Oops
-            error_logger:info_msg("eredis: Nothing in queue, but got value from parser~n"),
+            ?LOG_NOTICE("eredis: Nothing in queue, but got value from parser~n"),
```
Comment (bjosv) [inline src/eredis_client.erl:341]:
```suggestion
            ?LOG_NOTICE("Nothing in queue, but got value from parser"),
```
In this specific case `~n` will be printed to log since no arguments are given.

File: src/eredis_client.erl [hunk 4]
```diff
@@ -368,7 +370,8 @@ safe_send(Pid, Value) ->
     try erlang:send(Pid, Value)
     catch
         Err:Reason ->
-            error_logger:info_msg("eredis: Failed to send message to ~p with reason ~p~n", [Pid, {Err, Reason}])
+            ?LOG_NOTICE("eredis: Failed to send message to ~p with reason ~p~n",
```
Comment (bjosv) [inline src/eredis_client.erl:373]:
```suggestion
            ?LOG_NOTICE("Failed to send message to ~p with reason ~p",
```
Is there a reason to keep the newline in each log? Seems to be removed when using a formatter template anyway.

**Review by bjosv — COMMENTED** [review]
@e-kmisk Viktor is currently on vacation, but I can attempt to release a new eredis version and an eredis_cluster. I believe @zuiderkwast had an open question regarding removing `eredis: ` from the logs.
I also seen that the use of newline in the logs was not consistent in legacy.

Do you have any thoughts about removing newline and `eredis: ` from all logs before release?

**Comment by e-kmisk** [comment]
> @e-kmisk Viktor is currently on vacation, but I can attempt to release a new eredis version and an eredis_cluster. I believe @zuiderkwast had an open question regarding removing `eredis: ` from the logs. I also seen that the use of newline in the logs was not consistent in legacy.
> 
> Do you have any thoughts about removing newline and `eredis: ` from all logs before release?

As long as it is visible in the logs that eredis is the one reporting, I think we are happy with whatever is the most sane solution from erlang perspective.

**Comment by zuiderkwast** [comment]
If anyone is relying on "eredis:" in the logs, this change will require extra action from the user.

**Comment by bjosv** [comment]
> If anyone is relying on "eredis:" in the logs, this change will require extra action from the user.

You are right, as in system tests. Lets keep it.
