### PR TITLE
Terminate reconnect_loop process when client terminates

### LINKED ISSUE #124: Spawned reconnect_loop process is not terminated when the client is terminated
If an eredis client fails its first connection-attempt it will `spawn_link` a re-connection process.
This re-connection process will run until it succeeds.
But, if the connection attempts continuously fails and the user stops the eredis client, the spawned process is not terminated.
You will have an unexpected process running that attempts to connect to a previously used Redis instance.

A probable reason for this can be that eredis_client is stopped with reason `normal`, and an exit signal with reason `normal` is ignored by the re-connection process. See http://erlang.org/doc/reference_manual/processes.html#receiving-exit-signals

### PR DESCRIPTION
**Pull request by bjosv**
Resolves wooga/eredis#124

### CODE REVIEW

File: src/eredis_client.erl [hunk 1]
```diff
@@ -474,20 +476,24 @@ maybe_reconnect(Reason, #state{queue = Queue} = State) ->
...
-            [Client ! M || M <- Msgs];
-        {error, _Reason} ->
-            reconnect_loop(Client, State);
-        %% Something bad happened when connecting, like Redis might be
-        %% loading the dataset and we got something other than 'OK' in
-        %% auth or select
-        _ ->
-            reconnect_loop(Client, State)
+    receive
+        {'EXIT', _, Reason} -> exit(Reason)
```
Comment (zuiderkwast) [inline src/eredis_client.erl:480]: Here `_` is `Client`, right? We could be explicit here to make it easier to understand the code. Or at least a comment about when/why this can happen.

**Review by zuiderkwast — APPROVED** [review]
Nice!

File: src/eredis_client.erl (hunk 1 above)
Comment (bjosv) [reply src/eredis_client.erl]: Good, done

**Review by zuiderkwast — APPROVED** [review]
