### PR TITLE
Obfuscate secrets in state

### LINKED ISSUE #63: secrets should be obfuscated in eredis(_sub)_client gen_server state
A gen_server's state may be logged in error or crash reports so it should not directly contain secrets. The common best practice is wrapping secrets into functions that just return the secrets when invoked. 

See https://github.com/erlef/security-wg/blob/master/docs/secure_coding_and_deployment_hardening/sensitive_data.md#wrapping  (wrapping section)

The `auth_cmd` field of the gen_server state for these modules contains a secret (the password). Instead of directly storing the `AuthCmd` (which is a list of terms), a function could be stored that returns this list. Then the function can be invoked when the concrete value is needed.

Example:

```erl
init(Options) ->
   %% ...

    AuthCmd = get_auth_command(Username, Password),  % <- added

    State = #state{host = Host,
                   port = Port,
                   database = read_database(Database),
                   %% auth_cmd = get_auth_command(Username, Password),  % <- removed
                   auth_cmd_getter = fun() -> AuthCmd end,  % <- added
                   reconnect_sleep = ReconnectSleep,
                   connect_timeout = ConnectTimeout,
                   socket_options = SocketOptions,
                   tls_options = TlsOptions,
                   transport = Transport,

                   socket = undefined,
                   parser_state = eredis_parser:init(),
                   queue = queue:new()},
```

### PR DESCRIPTION
**Pull request by zuiderkwast**
Username and password are hidden in funs which are applied just when they are needed. This prevents the secrets from appearing verbatim in logs, stack traces, etc.

Fixes #63

### CODE REVIEW

**Comment by zuiderkwast** [comment]
@e-kmisk @dhruvjain99 I'm planning to release 1.6 which mainly adds sentinel support. I would be nice to include this one as well. Can you take a look quickly?

File: src/eredis_client.erl [hunk 1]
```diff
@@ -41,7 +41,7 @@
 -record(state, {
```
Comment (e-kmisk) [inline src/eredis_client.erl:41]: I guess eredis_client does not support code_change? Because if it does then the change in state would need to be handled I suppose?

File: src/eredis_client.erl [hunk 2]
```diff
@@ -606,12 +606,12 @@ read_database(Database) when is_integer(Database) ->
...
 get_auth_command(undefined, undefined) ->
     undefined;
 get_auth_command(undefined, "") -> % legacy
     undefined;
 get_auth_command(undefined, Password) ->
-    eredis:create_multibulk([<<"AUTH">>, Password]);
+    fun () -> eredis:create_multibulk([<<"AUTH">>, Password]) end;
 get_auth_command(Username, Password) ->
-    eredis:create_multibulk([<<"AUTH">>, Username, Password]).
+    fun () -> eredis:create_multibulk([<<"AUTH">>, Username, Password]) end.
```
Comment (e-kmisk) [inline src/eredis_client.erl:617]: This is slightly inefficient, because `eredis:create_multibulk/1` will be invoked every time the AuthCmd needs to be used, when we only need to do it once.

Maybe like this?

```erl
    get_auth_command(Username, Password) ->
        AuthCmd = eredis:create_multibulk([<<"AUTH">>, Username, Password]),
        fun () -> AuthCmd end.
```

File: src/eredis_client.erl (hunk 1 above)
Comment (zuiderkwast) [reply src/eredis_client.erl:41]: Good point! I think a code_change that turns an auth_cmd which is iodata into a fun might do...

Comment (zuiderkwast) [reply src/eredis_client.erl:41]: We've added `sentinel` to the state. It breaks code_change too, between versions before and after the addition of sentinel... @e-kmisk Do you need state conversion code for every version change?

Comment (zuiderkwast) [reply src/eredis_client.erl:41]: I've update `code_change/3` so that it succeeds only if the state record has not changed. Otherwise it fails with `{error, not_implemented}` which blocks the hot upgrade rather than crashing later. Better?

Comment (e-kmisk) [reply src/eredis_client.erl:41]: Seems ok to me.

Comment (zuiderkwast) [reply src/eredis_client.erl:41]: Good, so I consider this ready to merge. Agree?

**Comment by e-kmisk** [comment]
I guess that `eredis` should be prepared to receive the password as a function (with 0 args) too instead of plain text, as discussed in https://github.com/Nordix/eredis/issues/63

File: include/eredis.hrl [hunk 3]
```diff
@@ -6,6 +6,7 @@
 -type option() :: {host, string() | {local, string()}} |
                   {port, inet:port_number()} |
                   {database, integer()} |
+                  {username, string()} |
```
Comment (e-kmisk) [inline include/eredis.hrl:9]:
```erl
string() | fun(() -> string())
```

File: src/eredis_sentinel.erl [hunk 4]
```diff
@@ -181,8 +184,8 @@ query_master(#eredis_sentinel_state{conn_pid=undefined,
             ) ->
     case eredis:start_link([{host, H},
                             {port, P},
-                            {username, Username},
-                            {password, Password},
+                            {username, deobfuscate(Username)},
+                            {password, deobfuscate(Password)},
```
Comment (e-kmisk) [inline src/eredis_sentinel.erl:188]: If eredis accepts `fun(() -> string())` too then this is not necessary. 

As mentioned in the issue `start_link` seems to be one of the things that generates "PROGRESS REPORT" entries in erlang logs. So we don't want its arguments to be plain text ideally.

**Comment by e-kmisk** [comment]
I thought a bit more, there is an alternative with less coding and less legacy impact.

* if the library user passes a `fun(() -> string())` as value for password anywhere (in `eredis_cluster` or `eredis_sentinel` or `eredis_sub` etc.) then that should  propagate through the whole supervision tree and all states in its function form. The `AuthCmd` in `eredis_client` could be turned into a partially or fully resolved function, I don't have a strong preference, though obviously a fully resolved function is higher performance by some margin.
* if the library user passes a `string()` as password, everything can keep working as it does now (insecurely); this would be the most simple backwards compatible solution that doesn't even break `code_change` APIs (about this part my project don't really care, still just noting)
* optionally it can generate a warning and/or be documented that library users should pass  `fun(() -> string())` or `undefined` instead of `string()`

**Comment by zuiderkwast** [comment]
@e-kmisk

> if the library user passes a `fun(() -> string())` as value for password anywhere (in eredis_cluster or eredis_sentinel or eredis_sub etc.) then that should propagate through the whole supervision tree and all states in its function form.

This is a good point. We don't want cleartext secrets in the child_spec of any supervisor. Thus, I'll allow username and password in the fun form.

> if the library user passes a `string()` as password, everything can keep working as it does now (insecurely)

We're already adding sentinel options to the state in the same minor version, so state compatibility is broken anyway. I prefer to always store them obfuscated (wrapped in fun) in the state.

File: include/eredis.hrl (hunk 3 above)
Comment (zuiderkwast) [reply include/eredis.hrl]: changed to `iodata() | fun(() -> iodata()) | undefined`

File: src/eredis.erl [hunk 5]
```diff
@@ -48,8 +48,10 @@ start_link() ->
 %% socket as `{local, Path}' (available in OTP 19+); default `"127.0.0.1"'</dd>
 %% <dt>`{port, Port}'</dt><dd>Integer, default is 6379</dd>
 %% <dt>`{database, Database}'</dt><dd>Integer; 0 for the default database</dd>
-%% <dt>`{username, Username}'</dt><dd>String; default: no username</dd>
-%% <dt>`{password, Password}'</dt><dd>String; default: no password</dd>
+%% <dt>`{username, Username}'</dt><dd>String or a 0-ary function that returns
+%% the username; default: no username</dd>
```
Comment (e-kmisk) [inline src/eredis.erl:52]: Or the atom `undefined` right? Also maybe it's a good idea to phrase it like this:

> the atom `undefined` for no username or a 0-ary wrapping function that returns the username; default is `undefined`;  a value of type `iodata()` is also accepted but discouraged (the 0-ary function is preferred as the passed value may be logged in erlang reports)

Comment (zuiderkwast) [reply src/eredis.erl:52]: Thx. The most important information should be first IMO so I put the fun first and `undefined` last.

> A 0-ary function that returns the username (the preferred way to provide username as it prevent the actual username from appearing in logs and stacktraces), a string or iodata or the atom `undefined` for no username; default is `undefined`

**Comment by e-kmisk** [comment]
Looks good to me now. I guess a separate PR should be made later for `eredis_cluster` documenation to mention that 0-ary function is supported for username/pass there if eredis version is greater or equal to this version.

File: src/eredis_sub.erl [hunk 6]
```diff
@@ -56,8 +56,14 @@ start_link(Host, Port, Password, ReconnectSleep,
...
 %% <dt>`{port, Port}'</dt><dd>Integer, default is 6379</dd>
 %% <dt>`{database, Database}'</dt><dd>Integer; 0 for the default database</dd>
-%% <dt>`{username, Username}'</dt><dd>String; default: no username</dd>
-%% <dt>`{password, Password}'</dt><dd>String; default: no password</dd>
+%% <dt>`{username, Username}'</dt><dd>A 0-ary function that returns the username
+%% (the preferred way to provide username as it prevent the actual secret from
+%% appearing in logs and stacktraces), a string or iodata or the atom
+%% `undefined' for no username; default `undefined'</dd>
+%% <dt>`{password, Password}'</dt><dd>A 0-ary function that returns the password
+%% (the preferred way to provide password as it prevent the actual secret from
```
Comment (e-kmisk) [inline src/eredis_sub.erl:64]: typo "prevent" -> "prevents", applies in every description

**Comment by e-kmisk** [comment]
Could the doc update part also be done in the `eredis_cluster` upstream? There is no code impact in `eredis_cluster` (already tried and 0.8.0 works fine), only impact should be just updating the manual to also recommend using wrapped secrets.

Maybe it can be done once 1.7.0 eredis is released and upgraded to in that project?
